spring.application.name=DemoAnalyzer

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.connection-timeout=300000
server.tomcat.keep-alive-timeout=300000

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# PostgreSQL connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Settings
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server port
server.port=${SPRING_PORT:8080}

# Error stacktrace
server.error.include-stacktrace=never