spring.application.name=DemoAnalyzer

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

server.tomcat.connection-timeout=300000
server.tomcat.keep-alive-timeout=300000

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000